server:
  port: 8001

spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://59.110.48.246:3309/springcloud?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: carrotsql321
  mvc:
    throw-exception-if-no-handler-found: true



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.carrot.testcloud.entities


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#spring:
#  mvcthrow-exception-if-no-handler-found=true
#  spring.resources.add-mappings=false

