spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.109:3306/springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


    schema:
      -classpath:sql/department.sql
    initialization-mode: always


    druid:
      # 连接池配置
      # 配置初始化大小、最小、最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 3000
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      pool-prepared-statements: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall,slf4j
      # 配置web监控,默认配置也和下面相同(除用户名密码，enabled默认false外)，其他可以不配
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: root
        allow: 127.0.0.1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    jpa:
      repositories:
        enabled: true


mybatis:
  config-location: classpath:mybatis/mybatisconfig.xml
  mapper-locations: classpath:mybatis/employee.xml



---
#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://192.168.0.107:3306/springboot?serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always
#    type: com.alibaba.druid.pool.DruidDataSource
#    schema:
#      - classpath:sql/department.sql
#      - classpath:sql/employee.sql
#    druid:
#      # 连接池配置
#      # 配置初始化大小、最小、最大
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
#      # 配置获取连接等待超时的时间
#      max-wait: 3000
#      validation-query: SELECT 1 FROM DUAL
#      test-on-borrow: false
#      test-on-return: false
#      test-while-idle: true
#      pool-prepared-statements: true
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      filters: stat,wall,slf4j
#      # 配置web监控,默认配置也和下面相同(除用户名密码，enabled默认false外)，其他可以不配
##      web-stat-filter:
##        enabled: true
##        url-pattern: /*
##        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        login-username: admin
#        login-password: root
#        allow: 127.0.0.1

---

#spring:
#  datasource:
#    url: jdbc:mysql://192.168.0.107:3306/springboot
#    initialization-mode: always
#    hikari:
#        username: root
#        password: 123456
#        schema:
#          - classpath: department
#    data-username: root
#    data-password: 123456
#    type: com.mysql.cj.jdbc.MysqlDataSource


server:
  tomcat:
    uri-encoding: utf-8
---
server:
  port: 8080
spring:
  profiles:
    active: default
---
server:
  port: 8081
spring:
  profiles: dev
---

server:
  port: 8083
spring:
  profiles: prod
---
persion:
  lastName: lisi
  age: 13
  Date: 2019/07/22
  List:
    - lisi
    - zhaoliu
