server:
  port: 8080
spring:
  profiles:
    active: default
---
server:
  port: 8081
spring:
  profiles: dev
---

server:
  port: 8083
spring:
  profiles: prod
---
persion:
  lastName: lisi
  age: 13
  Date: 2019/07/22
  List:
    - lisi
    - zhaoliu
